# Generated by Django 4.0.10 on 2024-03-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
