# Generated by Django 4.0.10 on 2024-03-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquotation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='d_quotation',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost'),
        ),
    ]
