# Generated by Django 4.0.10 on 2024-04-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customquotation_cost_d_quotation_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='Payment ID')),
                ('signature', models.CharField(max_length=100, verbose_name='Signature')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='Payment Status')),
            ],
        ),
    ]
