# Generated by Django 4.0.10 on 2024-04-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quo',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
