# Generated by Django 4.0.10 on 2024-03-12 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffs',
        ),
    ]
