# Generated by Django 4.0.10 on 2024-03-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_staff_staffs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
