# Generated by Django 4.0.10 on 2024-03-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
