# Generated by Django 4.0.10 on 2024-03-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_delete_staffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=100, unique=True)),
                ('material_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('substrate_thickness', models.DecimalField(decimal_places=2, max_digits=10)),
                ('copper_thickness', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
