"""
Django settings for quotations project.

Generated by 'django-admin startproject' using Django 4.0.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR2 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR=os.path.join(BASE_DIR2,'templates')
Static_Dir=os.path.join(BASE_DIR2,'static')

PANEL_SIZE=300
SETUP_TIME=60
SINGLE_SIDED_PCB_TIME =30
MATERIAL_COSTS = {
    'material 1': 0.1,  # Cost per piece for material1
    'material 2': 0.2,  # Cost per piece for material2
    # Add more materials and costs as needed
}
COPPER_THICKNESS_COSTS = {
    'copper 1': 5,   # Cost for 25um copper thickness
    'copper 2': 8,   # Cost for 35um copper thickness
    # Add more thicknesses and costs as needed
}

SUBSTRATE_THICKNESS_COSTS = {
    'thickness 1': 20,   # Cost for 0.1mm substrate thickness
    'thickness 2': 30,   # Cost for 0.2mm substrate thickness
    # Add more thicknesses and costs as needed
}

SINGLE_SIDED_PCB_COST = 50  # Cost for single-sided PCB
DOUBLE_SIDED_PCB_COST = 80  # Cost for double-sided PCB

SURFACE_PAD_FINISH_COSTS = {
    'type1': {
        '3M tape': 5,   # Cost for 3MTAPE surface finish
        'HASL': 10,   # Cost for HASL surface finish
        'ENIG': 15,   # Cost for ENG surface finish
    },
    'type2': [
        'PTH',   # Cost for PTH surface finish
        'Solder',   # Cost for Solder surface finish
        'Tin coating',   # Cost for Tin coating surface finish
    ]
}
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cz^gtwij46po4-(06+0&3*0ayw96_a4jmwus6924626j(r5f23'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paypal.standard.ipn',
    'customer',
    'staff'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quotations.urls'
PAYPAL_CLIENT_ID = 'AcYhFdm-vu6DL6fq08QXeA7OKC11YXC4UrJYSqbvNOCEV4BoYgSnzYtQcdsgr3FQg9KgY9s2BQyilUSB'
PAYPAL_SECRET = 'EGE-0c2dih7-hd5HtyP1GKY50HvEPUXptTmqwO_iWJQxzR-GRxx63ZJCnO_IJyqjSGn9vuS1uFf3EErj'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quotations.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[BASE_DIR/"static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server host (e.g., 'smtp.gmail.com' for Gmail)
EMAIL_PORT = 587  # SMTP server port (587 is the default port for TLS)
EMAIL_USE_TLS = True  # Enable TLS (Transport Layer Security) encryption
# EMAIL_HOST_USER = 'balajisankar0202@gmail.com'  # Your email address
# EMAIL_HOST_PASSWORD = 'xmgk qami ghxu bmgs'  # Your email password
EMAIL_RECEIVING_USER=['to@gmail.com']



EMAIL_HOST_USER = 'kavyarajangam21@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'zijp ezhp lchb gvpf' 

RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET")